### PR TITLE
refactor(module): ajax load dpd-module list from http://npm.dathub.org/

### PR DESCRIPTION
**Pull request by ericfong**
No longer need to cache the module list in file

### CODE REVIEW

**Comment by NicolasRitouet** [comment]
@ericfong It looks like this PR got a bit lost, is it still relevant?
Should I merge it?

**Comment by NicolasRitouet** [comment]
Looks like dathub.org is down, any alternative?

**Comment by ericfong** [comment]
Mmm, hard to find npm repo mirror that allow Access-Control-Allow-Origin ...

**Comment by cognitom** [comment]
@ericfong how about npmsearch?
https://github.com/solids/npmsearch

Here is an example use case in [gulp](http://gulpjs.com/plugins/).
https://github.com/gulpjs/plugins/blob/master/src/scripts/controller/pluginList.js#L27-L38


BTW, the page is down for a while because of dathub. Something weird.
http://docs.deployd.com/modules/

> XMLHttpRequest cannot load http://npm.dathub.org/api/rows?start=dpd-. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://docs.deployd.com' is therefore not allowed access.

Even if [calling url](http://npm.dathub.org/api/rows?start=dpd-) directly, we could get nothing:

```
{
  "dat": true,
  "version": "7.0.4"
}
```

**Comment by ericfong** [comment]
The problem is we don't have a real server for the doc. We just using github page for that. Any help on that? 

Just a simple cross domain ajax call....

**Comment by cognitom** [comment]
@ericfong npmsearch allows access from any site. Looks enough...?

```javascript
res.setHeader('Access-Control-Allow-Origin', '*');
```

https://github.com/solids/npmsearch/blob/master/lib/routes.js#L32

**Comment by ericfong** [comment]
Oh, you mean directly ajax http://npmsearch.com/

Sorry, I am thinking you want to setup an npmsearch server when you point me to the github repo of npmsearch.

Yes. that may work. Thanks for your suggestion

**Comment by cognitom** [comment]
:smile:

**Comment by ericfong** [comment]
Updated

**Comment by cognitom** [comment]
Thank you so much! :tada:

**Pull request closed without merging**
